[versions]

# Plugins
kotlin = "2.3.0"
composePlugin = "1.11.0"

#Libraries
kotlinxCoroutines = "1.10.2"
mppKtx = "0.1.4"
moquette = "0.17"

[libraries]
kotlinxCoroutinesCore =  { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
mppKtx =  { module = "com.github.kotlinizer.mpp-ktx:mpp-ktx", version.ref = "mppKtx" }
moquette = { module = "io.moquette:moquette-broker", version.ref = "moquette" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
